export interface Flight {
  id: string;
  airline_name: string;
  airline_code?: string;
  airline_logo: string;
  price: number;
  currency?: string; // "USD" for live API results, "PHP" for mock data
  duration: string;
  duration_minutes: number;
  departure_time: string;
  arrival_time: string;
  booking_url: string;
  flight_type: string;
}

export const MOCK_FLIGHTS: Flight[] = [
  {
    id: "fl-001",
    airline_name: "Philippine Airlines",
    airline_code: "PR",
    airline_logo: "https://logo.clearbit.com/philippineairlines.com",
    price: 3499,
    duration: "1h 15m",
    duration_minutes: 75,
    departure_time: "05:45 AM",
    arrival_time: "07:05 AM",
    flight_type: "Direct",
    booking_url: "https://www.philippineairlines.com",
  },
  {
    id: "fl-002",
    airline_name: "Cebu Pacific",
    airline_code: "5J",
    airline_logo: "https://logo.clearbit.com/cebupacificair.com",
    price: 2899,
    duration: "1h 20m",
    duration_minutes: 80,
    departure_time: "06:30 AM",
    arrival_time: "07:50 AM",
    flight_type: "Direct",
    booking_url: "https://www.cebupacificair.com",
  },
  {
    id: "fl-003",
    airline_name: "AirAsia Philippines",
    airline_code: "Z2",
    airline_logo: "https://logo.clearbit.com/airasia.com",
    price: 3850,
    duration: "1h 15m",
    duration_minutes: 75,
    departure_time: "08:00 AM",
    arrival_time: "09:15 AM",
    flight_type: "Direct",
    booking_url: "https://www.airasia.com",
  },
  {
    id: "fl-004",
    airline_name: "Philippine Airlines",
    airline_code: "PR",
    airline_logo: "https://logo.clearbit.com/philippineairlines.com",
    price: 4200,
    duration: "1h 10m",
    duration_minutes: 70,
    departure_time: "10:15 AM",
    arrival_time: "11:25 AM",
    flight_type: "Direct",
    booking_url: "https://www.philippineairlines.com",
  },
  {
    id: "fl-005",
    airline_name: "Cebu Pacific",
    airline_code: "5J",
    airline_logo: "https://logo.clearbit.com/cebupacificair.com",
    price: 2650,
    duration: "1h 25m",
    duration_minutes: 85,
    departure_time: "12:00 PM",
    arrival_time: "01:25 PM",
    flight_type: "Direct",
    booking_url: "https://www.cebupacificair.com",
  },
  {
    id: "fl-006",
    airline_name: "AirAsia Philippines",
    airline_code: "Z2",
    airline_logo: "https://logo.clearbit.com/airasia.com",
    price: 3150,
    duration: "1h 20m",
    duration_minutes: 80,
    departure_time: "02:30 PM",
    arrival_time: "03:50 PM",
    flight_type: "Direct",
    booking_url: "https://www.airasia.com",
  },
  {
    id: "fl-007",
    airline_name: "Philippine Airlines",
    airline_code: "PR",
    airline_logo: "https://logo.clearbit.com/philippineairlines.com",
    price: 5100,
    duration: "1h 10m",
    duration_minutes: 70,
    departure_time: "04:00 PM",
    arrival_time: "05:10 PM",
    flight_type: "Direct",
    booking_url: "https://www.philippineairlines.com",
  },
  {
    id: "fl-008",
    airline_name: "Cebu Pacific",
    airline_code: "5J",
    airline_logo: "https://logo.clearbit.com/cebupacificair.com",
    price: 3499,
    duration: "1h 30m",
    duration_minutes: 90,
    departure_time: "05:45 PM",
    arrival_time: "07:15 PM",
    flight_type: "Direct",
    booking_url: "https://www.cebupacificair.com",
  },
  {
    id: "fl-009",
    airline_name: "AirAsia Philippines",
    airline_code: "Z2",
    airline_logo: "https://logo.clearbit.com/airasia.com",
    price: 2999,
    duration: "1h 15m",
    duration_minutes: 75,
    departure_time: "07:00 PM",
    arrival_time: "08:15 PM",
    flight_type: "Direct",
    booking_url: "https://www.airasia.com",
  },
  {
    id: "fl-010",
    airline_name: "Philippine Airlines",
    airline_code: "PR",
    airline_logo: "https://logo.clearbit.com/philippineairlines.com",
    price: 4750,
    duration: "1h 10m",
    duration_minutes: 70,
    departure_time: "08:30 PM",
    arrival_time: "09:40 PM",
    flight_type: "Direct",
    booking_url: "https://www.philippineairlines.com",
  },
  {
    id: "fl-011",
    airline_name: "Cebu Pacific",
    airline_code: "5J",
    airline_logo: "https://logo.clearbit.com/cebupacificair.com",
    price: 2450,
    duration: "1h 35m",
    duration_minutes: 95,
    departure_time: "09:00 PM",
    arrival_time: "10:35 PM",
    flight_type: "Direct",
    booking_url: "https://www.cebupacificair.com",
  },
  {
    id: "fl-012",
    airline_name: "AirAsia Philippines",
    airline_code: "Z2",
    airline_logo: "https://logo.clearbit.com/airasia.com",
    price: 3299,
    duration: "1h 20m",
    duration_minutes: 80,
    departure_time: "10:00 PM",
    arrival_time: "11:20 PM",
    flight_type: "Direct",
    booking_url: "https://www.airasia.com",
  },
];
